	{level "lvl_1"
		{stand
			{accuracy 1.00}
		}
		{squat
			{accuracy 1.20}
		}
		{crawl
			{accuracy 1.40}
		}
		{cover
			{accuracy 1.50}
		}
		{vehicle
			{accuracy 2.00}
		}
	}
	{level "lvl_2"
		{stand
			{accuracy 1.25}
		}
		{squat
			{accuracy 1.45}
		}
		{crawl
			{accuracy 1.65}
		}
		{cover
			{accuracy 1.75}
		}
		{vehicle
			{accuracy 2.25}
		}
	}
	{level "lvl_3"
		{stand
			{accuracy 1.50}
		}
		{squat
			{accuracy 1.70}
		}
		{crawl
			{accuracy 1.90}
		}
		{cover
			{accuracy 2.00}
		}
		{vehicle
			{accuracy 2.50}
		}
	}
	{level "lvl_4"
		{stand
			{accuracy 1.75}
		}
		{squat
			{accuracy 1.95}
		}
		{crawl
			{accuracy 2.15}
		}
		{cover
			{accuracy 2.25}
		}
		{vehicle
			{accuracy 2.75}
		}
	}
	{level "lvl_5"
		{stand
			{accuracy 1.80}
		}
		{squat
			{accuracy 2.00}
		}
		{crawl
			{accuracy 2.20}
		}
		{cover
			{accuracy 2.30}
		}
		{vehicle
			{accuracy 2.80}
		}
	}