{easy
	{balancingFactorBonus {cp 0.75} {mp 0.75} {payback 0.75} }
	{chargeFactors
		{value "*=0"}
	}
}
{normal
	{balancingFactorBonus {cp 1.00} {mp 1.00} {payback 1.00} }
	{chargeFactors
		{value "*=0"}
	}
}
{hard
	{balancingFactorBonus {cp 1.25} {mp 1.50} {payback 1.50} }
	{chargeFactors
		{value "*=0"}
	}
}
{heroic
	{balancingFactorBonus {cp 1.50} {mp 2.00} {payback 2.00} }
	{chargeFactors
		{value "*=0"}
	}
}